fix: Prevent destruction of topic ACLs [DEVOP-5504]
honestbank/terraform-confluent-kafka pull request #25
Opened 2024-11-27 09:55 UTC by ChristianWitts

Please confirm that you have done the following before requesting reviews:

- [x] I have confirmed that the PR type is appropriate for the change I am making according to the [Honest Pull Request and Commit Message Naming Conventions](https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c).
- [x] I have typed an adequate description that explains **why** I am making this change.
- [x] I have installed and run standard pre-commit hooks that lints and validates my code.

### Description

Currently there are a lot of ACLs that share the same ID due
to them using the `PREFIX` pattern type, but still created in
state for all the topics utilising that `PREFIX` which can lead
to accidental unavailability if you delete one of the topics that
utilises that ACL identifier.

In order to block accidental deletion and unavailability, we will
set the `prevent_destroy` lifecycle policy so that any destruction
events will rather error out the plan/apply.

The long-term solution will be of two parts;
1. Migrate the ACL resources to their own module, such that in cases
   like `PREFIX` patterns can be managed once, instead of `n` times,
2. A thorough design session to implement tighter access controls in
   order to move towards a better segmented access policy.

Refs: #DEVOP-5504

Signed-off-by: Christian Witts <christian@honestbank.com>

2024-11-27 09:56 UTC, jeremyrajan approved these changes, later dismissed

2024-11-27 09:57 UTC, sunilhonest approved these changes, later dismissed

2024-11-27 09:59 UTC, maetolay approved these changes, later dismissed

2024-11-27 10:11 UTC, jai requested changes
Please update/fix tests

2024-12-16 09:32 UTC, ChristianWitts commented
Superceded by #27

2024-12-16 09:32 UTC, closed without merging