feat: revert provider change and remove unused variable | DEVOP-5562"
honestbank/terraform-confluent-kafka pull request #28
Opened 2024-12-11 12:22 UTC by bibek4699

Please confirm that you have done the following before requesting reviews:

- [x] I have confirmed that the PR type is appropriate for the change I am making according to the [Honest Pull Request and Commit Message Naming Conventions](https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c).
- [x] I have typed an adequate description that explains **why** I am making this change.
- [x] I have installed and run standard pre-commit hooks that lints and validates my code.

### Description

This PR reverts the changes made to the Confluent provider in the Terraform configuration and removes unused variables. The revert is necessary due to critical bugs encountered in the latest version of the Confluent provider (v2.12.0), which result in frequent timeouts and failed requests when interacting with Confluent Cloud.

https://app.terraform.io/app/honestbank/workspaces/kafka-infrastructure-dev/runs/run-w1p1jyAfJzxRcR6W

```
2024-12-11T12:03:52.918Z [ERROR] provider.terraform-provider-confluent_2.12.0: request failed: tf_req_id=ad7696a8-1730-0102-bede-ed69542e3b26 tf_rpc=Configure url=https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/topics/decisioning.manual-pep.create-ticket-request.success.avro @caller=src/github.com/confluentinc/terraform-provider-confluent/internal/provider/factory_utils.go:182 @module=provider tf_provider_addr=provider error="Get \"https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/topics/decisioning.manual-pep.create-ticket-request.success.avro\": dial tcp 34.101.104.100:443: i/o timeout" method=GET timestamp=2024-12-11T12:03:52.917Z
2024-12-11T12:04:04.153Z [ERROR] provider.terraform-provider-confluent_2.12.0: request failed: @module=provider tf_rpc=Configure url="https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=READ&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.card-delivery.order-placed.deadletter.avro&resource_type=TOPIC" @caller=src/github.com/confluentinc/terraform-provider-confluent/internal/provider/factory_utils.go:182 error="Get \"https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=READ&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.card-delivery.order-placed.deadletter.avro&resource_type=TOPIC\": dial tcp 34.101.104.100:443: i/o timeout" method=GET tf_provider_addr=provider tf_req_id=ad7696a8-1730-0102-bede-ed69542e3b26 timestamp=2024-12-11T12:04:04.153Z
2024-12-11T12:04:04.179Z [ERROR] provider.terraform-provider-confluent_2.12.0: request failed: method=GET tf_provider_addr=provider @caller=src/github.com/confluentinc/terraform-provider-confluent/internal/provider/factory_utils.go:182 error="Get \"https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.card-delivery.order-placed.deadletter.avro&resource_type=TOPIC\": dial tcp 34.101.104.100:443: i/o timeout" tf_req_id=ad7696a8-1730-0102-bede-ed69542e3b26 tf_rpc=Configure url="https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.card-delivery.order-placed.deadletter.avro&resource_type=TOPIC" @module=provider timestamp=2024-12-11T12:04:04.179Z
2024-12-11T12:04:04.202Z [ERROR] provider.terraform-provider-confluent_2.12.0: request failed: url="https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.card-delivery.order-placed.retry.avro&resource_type=TOPIC" @caller=src/github.com/confluentinc/terraform-provider-confluent/internal/provider/factory_utils.go:182 error="Get \"https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.card-delivery.order-placed.retry.avro&resource_type=TOPIC\": dial tcp 34.101.104.100:443: i/o timeout" method=GET tf_provider_addr=provider tf_req_id=ad7696a8-1730-0102-bede-ed69542e3b26 tf_rpc=Configure @module=provider timestamp=2024-12-11T12:04:04.202Z
2024-12-11T12:04:04.203Z [ERROR] provider.terraform-provider-confluent_2.12.0: request failed: @caller=src/github.com/confluentinc/terraform-provider-confluent/internal/provider/factory_utils.go:182 @module=provider method=GET url="https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.card-delivery.order-placed.success.avro&resource_type=TOPIC" tf_req_id=ad7696a8-1730-0102-bede-ed69542e3b26 tf_rpc=Configure error="Get \"https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.card-delivery.order-placed.success.avro&resource_type=TOPIC\": dial tcp 34.101.104.100:443: i/o timeout" tf_provider_addr=provider timestamp=2024-12-11T12:04:04.203Z
2024-12-11T12:04:05.130Z [ERROR] provider.terraform-provider-confluent_2.12.0: request failed: @module=provider tf_provider_addr=provider tf_rpc=Configure url="https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.cms-card-repayment-service.eod.process-fnx-dw-to-rudderstack.dead-letter.avro&resource_type=TOPIC" @caller=src/github.com/confluentinc/terraform-provider-confluent/internal/provider/factory_utils.go:182 tf_req_id=ad7696a8-1730-0102-bede-ed69542e3b26 error="Get \"https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.cms-card-repayment-service.eod.process-fnx-dw-to-rudderstack.dead-letter.avro&resource_type=TOPIC\": dial tcp 34.101.104.100:443: i/o timeout" method=GET timestamp=2024-12-11T12:04:05.129Z
2024-12-11T12:04:05.624Z [ERROR] provider.terraform-provider-confluent_2.12.0: request failed: method=GET tf_provider_addr=provider tf_rpc=Configure @module=provider tf_req_id=ad7696a8-1730-0102-bede-ed69542e3b26 url="https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.post-repayment.repayment-processing.retry.avro&resource_type=TOPIC" @caller=src/github.com/confluentinc/terraform-provider-confluent/internal/provider/factory_utils.go:182 error="Get \"https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.post-repayment.repayment-processing.retry.avro&resource_type=TOPIC\": dial tcp 34.101.104.100:443: i/o timeout" timestamp=2024-12-11T12:04:05.624Z
2024-12-11T12:04:06.279Z [ERROR] provider.terraform-provider-confluent_2.12.0: request failed: error="Get \"https://pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:443/kafka/v3/clusters/lkc-o3gv9x/acls?host=%2A&operation=WRITE&pattern_type=LITERAL&permission=ALLOW&principal=User%3Asa-63npm8&resource_name=self-service.post-repayment.repayment-processing.deadletter.avro&resource_type=TOPIC\": dial tcp 34.101.104.100:443: i/o timeout" method=GET tf_provider_addr=provider u [...]

2024-12-11 13:16 UTC, ChristianWitts requested changes

2024-12-11 13:16 UTC, ChristianWitts commented on modules/cluster-admin/providers.tf
> +      version = "~>1.0.0"
This will pin the version to only `v1.0.x` providers, which we do not want. You will want `~> 1.0`. Also please include the space.

2024-12-12 03:08 UTC, sunilhonest approved these changes

2024-12-12 03:53 UTC, ChristianWitts approved these changes

2024-12-12 03:53 UTC, merged